"""init

Revision ID: 44f9df8c38a7
Revises: e93ddc7903b0
Create Date: 2023-08-18 16:04:40.580137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f9df8c38a7'
down_revision = 'e93ddc7903b0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
